# Auto-generated by .github/workflows/release.yml.
# Hand-edits will be overwritten on the next release.
class SmtpTestTool < Formula
  desc "Cross-platform SMTP / IMAP / POP3 connectivity tester with IT-actionable diagnostics"
  homepage "https://github.com/Struis112/smtp-test-tool"
  version "0.0.0"
  license any_of: ["MIT", "Apache-2.0"]

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/Struis112/smtp-test-tool/releases/download/v0.0.0/smtp-test-tool-aarch64-apple-darwin.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  elsif OS.mac?
    url "https://github.com/Struis112/smtp-test-tool/releases/download/v0.0.0/smtp-test-tool-x86_64-apple-darwin.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  elsif OS.linux?
    url "https://github.com/Struis112/smtp-test-tool/releases/download/v0.0.0/smtp-test-tool-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  def install
    bin.install "smtp-test-tool"
    bin.install "smtp-test-tool-gui" if File.exist?("smtp-test-tool-gui")
  end

  test do
    assert_match "smtp-test-tool", shell_output("#{bin}/smtp-test-tool --version")
  end
end
